AllCops:
  TargetRubyVersion: 2.0
  Exclude:
  - 'vendor/**/*'

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/MutableConstant:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20

# Allow long blocks in rspec
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
