AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - 'vendor/**/*'

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/MutableConstant:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# Not available in older rubies
Style/SafeNavigation:
  Enabled: false

# Disabled because it makes the code longer, more repetitive
Style/FormatStringToken:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 25

# Allow long blocks in rspec
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
